# Generated by Django 5.1.6 on 2025-09-28 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('color', models.CharField(default='#007bff', help_text='Hex rang kodi', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Qisqacha')),
                ('category', models.CharField(choices=[('tech', 'Texnologiya'), ('business', 'Biznes'), ('finance', 'Moliya'), ('startup', 'Startaplar'), ('investment', 'Investitsiya'), ('market', 'Bozor'), ('crypto', 'Kripto'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Manba havolasi')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='Manba nomi')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Rasm havolasi')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='Tezkor yangilik')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy yangilik')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Nashr vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
    ]
